const { chromium } = require("playwright");
const path = require("path");
const fs = require("fs");

const README_PATH = path.resolve("README.md");
const IMAGE_PATH = "images/readme";

function getReadmeHref(html, htmlPath) {
    const match = html.match(
        /<!--\s*readme-href=(.*?)\s*-->/
    );

    if (!match) {
        throw new Error(`Missing readme-href in ${htmlPath}`);
    }

    return match[1];
}

function generateReadme(parts) {
    const headerComment = `<!-- DO NOT EDIT THIS README; IT IS AUTO-GENERATED BY CI -->
<!-- Changes to this file will be lost if the file is regenerated -->`;

    const blocks = parts.map(part => `
<a href="${part.href}">
  <picture>
    <source
      media="(prefers-color-scheme: dark)"
      srcset="${IMAGE_PATH}/${part.imageName}-dark.webp"
    >
    <source
      media="(prefers-color-scheme: light)"
      srcset="${IMAGE_PATH}/${part.imageName}-light.webp"
    >
    <img
      src="${IMAGE_PATH}/${part.imageName}-light.webp"
      width="100%"
    >
  </picture>
</a>
`.trim());

    const content = [headerComment, ...blocks].join("\n\n") + "\n";

    fs.writeFileSync(
        README_PATH,
        content,
        "utf8"
    );
}

(async () => {
    const browser = await chromium.launch();
    const parts = [];

    let index = 0;

    while (true) {
        const htmlPath = path.resolve(`readme/part-${index}.html`);

        // Stop when the next part does not exist.
        if (!fs.existsSync(htmlPath)) {
            break;
        }

        const html = fs.readFileSync(htmlPath, "utf8");
        const href = getReadmeHref(html, htmlPath);

        const isFirst = index === 0;
        const isLast = !fs.existsSync(
            path.resolve(`readme/part-${index + 1}.html`)
        );

        // Middle image
        let paddingTop = "25px";
        let paddingBottom = "25px";

        // Only image
        if (isFirst && isLast) {
            paddingTop = "50px";
            paddingBottom = "50px";
        // First image
        } else if (isFirst) {
            paddingTop = "50px";
        // Last image
        } else if (isLast) {
            paddingBottom = "50px";
        }

        const imageName = `part-${index}`;

        for (const theme of ["light", "dark"]) {
            const page = await browser.newPage({
                viewport: {
                    width: 760,
                    height: 500
                },
                deviceScaleFactor: 2
            });

            await page.goto(`file://${htmlPath}`);

            await page.addStyleTag({
                content: `
                    .page {
                        padding-top: ${paddingTop} !important;
                        padding-bottom: ${paddingBottom} !important;
                    }
                `
            });

            await page.evaluate(theme => {
                document.body.dataset.theme = theme;
            }, theme);

            await page.evaluate(() => document.fonts.ready);

            const element = page.locator(".page");
            const boundingBox = await element.boundingBox();

            if (boundingBox) {
                await page.screenshot({
                    path: `${IMAGE_PATH}/${imageName}-${theme}.webp`,
                    type: "webp",
                    quality: 95,
                    omitBackground: true,
                    clip: boundingBox
                });
            }

            await page.close();
        }

        parts.push({
            imageName,
            href
        });

        index++;
    }

    await browser.close();

    generateReadme(parts);
})();